CREATE DATABASE online_store;

USE online_store;

CREATE TABLE products (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	image VARCHAR(255) NOT NULL,
	price DECIMAL(10, 2) NOT NULL